server:
  port: 80
  max-http-header-size: 10240
beetl:
  delimiter-statement-start: \@
  delimiter-statement-end:
spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        timeout: 1000
mybatis-plus:
  mapper-locations:
    - classpath*:com/common/platform/**/mapping/*.xml
  typeAliasesPackage: com.common.platform.*.entity
  global-config:
    enable-sql-runner: true
log:
  path: _app_logs
mail:
  flag: false

login:
  session:
    cache:
      type: local

